package com.tripchat.dto.request;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.Getter;
import lombok.NoArgsConstructor;

import java.util.UUID;

/**
 * SendMessageRequest — payload sent by the client over STOMP.
 *
 * clientId:
 *   UUID generated by the client before sending.
 *   Idempotency key — if the client retries on network failure,
 *   the server deduplicates via ON CONFLICT (client_id) DO NOTHING.
 *   Client is responsible for generating a fresh UUID per unique message.
 *
 * content:
 *   Max 4000 chars — reasonable upper bound for a chat message.
 *   Enforced at the application layer before hitting the DB.
 */
@Getter
@NoArgsConstructor
public class SendMessageRequest {

    @NotNull(message = "clientId is required for idempotency")
    private UUID clientId;

    @NotBlank(message = "Message content cannot be empty")
    @Size(max = 4000, message = "Message content must not exceed 4000 characters")
    private String content;
}
