package com.tripchat.model;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.OnDelete;
import org.hibernate.annotations.OnDeleteAction;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.Instant;
import java.util.UUID;

/**
 * Message entity — maps to the `messages` table.
 *
 * Represents a single chat message sent in a group.
 *
 * group (ManyToOne LAZY, ON DELETE CASCADE):
 *   If a group is deleted, all its messages are deleted.
 *   FetchType.LAZY — we don't need the full Group object just to
 *   read a message. Loaded only when explicitly accessed in a transaction.
 *
 * sender (ManyToOne LAZY, ON DELETE SET NULL):
 *   If a user deletes their account, messages are preserved.
 *   sender becomes null — UI shows "Deleted User".
 *   nullable = true to allow SET NULL behaviour.
 *
 * clientId (UNIQUE):
 *   UUID generated by the client before sending.
 *   Idempotency key — INSERT ... ON CONFLICT (client_id) DO NOTHING
 *   prevents duplicate messages if the outbox relay publishes twice.
 *
 * deletedAt (soft delete):
 *   null = message is active.
 *   non-null = message was deleted — UI shows "This message was deleted".
 *   Preserves conversation context rather than leaving gaps.
 *
 * Index on (group_id, created_at DESC) WHERE deleted_at IS NULL:
 *   Covers the most frequent query — get recent messages for a group.
 *   Partial index — only non-deleted rows are indexed, keeping it small.
 */
@Entity
@Table(
    name = "messages",
    indexes = {
        @Index(
            name = "idx_messages_group_created",
            columnList = "group_id, created_at DESC"
        )
    }
)
@EntityListeners(AuditingEntityListener.class)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Message {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(updatable = false, nullable = false)
    private UUID id;

    // Which group this message belongs to
    // ON DELETE CASCADE: group deleted → all its messages deleted
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "group_id", nullable = false)
    @OnDelete(action = OnDeleteAction.CASCADE)
    private Group group;

    // Who sent the message — nullable for SET NULL on user delete
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "sender_id", nullable = true)
    private User sender;

    @Column(nullable = false, columnDefinition = "TEXT")
    private String content;

    // Client-generated UUID — idempotency key to prevent duplicate persists
    @Column(nullable = false, unique = true, updatable = false)
    private UUID clientId;

    @CreatedDate
    @Column(nullable = false, updatable = false)
    private Instant createdAt;

    // Soft delete — null = active, timestamp = deleted
    @Column
    private Instant deletedAt;
}
